# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  freetube = {
    pname = "freetube";
    version = "0.14.0";
    src = fetchurl {
      url = "https://github.com/FreeTubeApp/FreeTube/releases/download/v0.14.0-beta/freetube_0.14.0_amd64.AppImage";
      sha256 = "0qaghj70ffc90wck1i4217ky5d6cryrmgna2ipsc4v8dcvbyc1lh";
    };
  };
  looking-glass-client = {
    pname = "looking-glass-client";
    version = "B4";
    src = fetchgit {
      url = "https://github.com/gnif/LookingGlass";
      rev = "B4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0fwmz0l1dcfwklgvxmv0galgj2q3nss90kc3jwgf6n80x27rsnhf";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  starship = {
    pname = "starship";
    version = "v0.57.0";
    src = fetchgit {
      url = "https://github.com/starship/starship";
      rev = "v0.57.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1agv7xdsifkhd5g7zjqdw0v6784ka0261mjpd625lklrlwmw253k";
    };
  };
}
