# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  discord = {
    pname = "discord";
    version = "0.0.16";
    src = fetchurl {
      url = "https://dl.discordapp.net/apps/linux/0.0.16/discord-0.0.16.tar.gz";
      sha256 = "1s9qym58cjm8m8kg3zywvwai2i3adiq6sdayygk2zv72ry74ldai";
    };
  };
  freetube = {
    pname = "freetube";
    version = "0.15.0";
    src = fetchurl {
      url = "https://github.com/FreeTubeApp/FreeTube/releases/download/v0.15.0-beta/freetube_0.15.0_amd64.AppImage";
      sha256 = "0cwwi03qhrpy6525lcf5ryy83g6vwm6pdwjanhy4wkw1fiiiarz7";
    };
  };
  idea-ultimate = {
    pname = "idea-ultimate";
    version = "2021.2.3";
    src = fetchurl {
      url = "https://download.jetbrains.com/idea/ideaIU-2021.2.3-no-jbr.tar.gz";
      sha256 = "1d0kk2yydrbzvdy6dy9jqr182panidmbf2hy80gvi5ph2r5rv1qd";
    };
  };
  looking-glass-client = {
    pname = "looking-glass-client";
    version = "B4";
    src = fetchgit {
      url = "https://github.com/gnif/LookingGlass";
      rev = "B4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0fwmz0l1dcfwklgvxmv0galgj2q3nss90kc3jwgf6n80x27rsnhf";
    };
  };
  lutris = {
    pname = "lutris";
    version = "v0.5.9.1";
    src = fetchgit {
      url = "https://github.com/lutris/lutris";
      rev = "v0.5.9.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1v9ml5s17brr9hryc58y8cpga5li9y7hxi0zsfpm4v4aw2fwjhya";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  starship = {
    pname = "starship";
    version = "v0.58.0";
    src = fetchgit {
      url = "https://github.com/starship/starship";
      rev = "v0.58.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "127q3z7gjv2zsmrik5i7m7wpyyr4r0w02ilnmk2mwk5jj0i1zkmk";
    };
  };
  webstorm = {
    pname = "webstorm";
    version = "2021.2.2";
    src = fetchurl {
      url = "https://download.jetbrains.com/webstorm/WebStorm-2021.2.2.tar.gz";
      sha256 = "1a3vlqza9nbc4a2qxrzdckmq003zx1db9dy7wx462amc8sbh6v92";
    };
  };
}
